version: '3.9'

services:
  client:
    image: client
    container_name: client
    build:
      context: ./client/
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost:4001
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:4001
    depends_on:
      - server
    ports:
      - '3001:3000'
    networks:
      - myNetwork

  database:
    build:
      context: ./database/
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - myNetwork

  server:
    image: server
    container_name: server
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    ports:
      - '4001:4000'
    depends_on:
      - database
    environment:
      DB_DIALECT: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: nest
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
